### ISSUE TITLE
UpdateSeuratObject() does not create the new Layer-structure of Seurat v5+

### ISSUE THREAD

**Issue by vertesy** [satijalab/seurat-object#193]
Hello,

maybe this is expected behavior, but I was surprised when I updating an object `v3.99` to `v5.0.1` that the new object still contained the old data structure: slots instead layers.

#### Update
```r
> combined.obj.after@version
[1] ‘3.9.9.9010’

> obj.Fig.4D <- UpdateSeuratObject(combined.obj.after )
Validating object structure
Updating object slots
Ensuring keys are in the proper structure
Updating matrix keys for DimReduc ‘pca’
Updating matrix keys for DimReduc ‘umap’
Warning: Assay RNA changing from Assay to Assay
Warning: Assay integrated changing from Assay to Assay
Warning: Assay alra changing from Assay to Assay
Ensuring keys are in the proper structure
Ensuring feature names dont have underscores or pipes
Updating slots in RNA
Updating slots in integrated
Updating slots in alra
Updating slots in integrated_nn
Setting default assay of integrated_nn to integrated
Updating slots in integrated_snn
Setting default assay of integrated_snn to integrated
Updating slots in pca
Updating slots in umap
Setting umap DimReduc to global
No assay information could be found for FindIntegrationAnchors
No assay information could be found for withCallingHandlers
No assay information could be found for RunTSNE
Setting assay used for FindVariableFeatures.integrated to integrated
Setting assay used for ScaleData.integrated to integrated
Setting assay used for RunPCA.integrated to integrated
Setting assay used for RunUMAP.integrated.pca to integrated
Setting assay used for FindNeighbors.integrated.pca to integrated
No assay information could be found for FindClusters
Validating object structure for Assay ‘RNA’
Validating object structure for Assay ‘integrated’
Validating object structure for Assay ‘alra’
Validating object structure for Graph ‘integrated_nn’
Validating object structure for Graph ‘integrated_snn’
Validating object structure for DimReduc ‘pca’
Validating object structure for DimReduc ‘umap’
Object representation is consistent with the most current Seurat version
Warning messages:
1: Adding a command log without an assay associated with it 
2: Adding a command log without an assay associated with it 
3: Adding a command log without an assay associated with it 
4: Adding a command log without an assay associated with it 

> obj.Fig.4D@version
[1] ‘5.0.1’

```

#### Expected: Layer-structure of Seurat v5+
```r
> (otherv5.obj@assays$RNA)
Assay (v5) data with 30753 features for 162615 cells
Top 10 variable features:
 TTR, KRT19, SLPI, S100A9 ...
Layers:
 scale.data, data, counts 
```

#### Observed
```r
> obj.Fig.4D@assays$RNA
Assay data with 26690 features for 5478 cells
First 10 features:
 AL627309.1, AL669831.5, LINC00115, FAM41C, AL645608.7, AL645608.1, SAMD11, NOC2L, KLHL17, AL645608.8 
> combined.obj.after@assays$RNA
Assay data with 26690 features for 5478 cells
First 10 features:
 AL627309.1, AL669831.5, LINC00115, FAM41C, AL645608.7, AL645608.1, SAMD11, NOC2L, KLHL17, AL645608.8 
> 
```

- [ ] maybe this is related to the `Warnings` → in this case, how to perform a proper update?

Thank you for your time and continued work on the package!

**Comment by vertesy** [comment]
Maybe the issue title is misleading, but there is sth "unexpected" with the internal data structure.

```r
> dim(otherv5.obassays[["RNA"]]@layers$scale.data)
[1] 2000 8130
```

versus
```r
> dim(obj.Fig.4D@assays[["RNA"]]@layers$scale.data)
Error: no slot of name "layers" for this object of class "Assay"
> dim(obj.Fig.4D@assays[["integrated"]]@layers$scale.data)
Error: no slot of name "layers" for this object of class "Assay"
```

**Comment by mojaveazure** [comment]
Hi Abel and Robert,

`UpdateSeuratObject()` is not intended to transform internal assays from the v3 spec to the v5 spec. Given that conversion between the two assays is one-way only from v3 to v5, we opted not to include this specific conversion in `UpdateSeuratObject()`

What `UpdateSeuratObject()` is intended for is to ensure that the class definition of the overarching `Seurat` object is up-to-date. We have, in the past, added new slots to the `Seurat` object and given R's caching of class definitions, we built this function to take care of ensuring the slots and class definition are up-to-date. As v3 assays are explicitly allowed in a v5 object, and given the one-way conversion issue mentioned above, having `UpdateSeuratObject()` automatically cast v3 assays to v5 assays would be out-of-scope

To convert your assays from the v3 spec to the v5 spec, you can run
```R
object[["assay_name"]] <- as(object[["assay_name", class = "Assay5")
```

For example
```R
> data("pbmc_small")
> pbmc_small[["RNA"]] <- as(pbmc_small[["RNA"]], Class = "Assay5")
Warning: Assay RNA changing from Assay to Assay5
> pbmc_small[["RNA"]]
Assay (v5) data with 230 features for 80 cells
Top 10 variable features:
 PPBP, IGLL5, VDAC3, CD1C, AKR1C3, PF4, MYL9, GNLY, TREML1, CA2
Layers:
 data, counts, scale.data
```

If you'd like to keep the v3 and v5 assays side-by-side, this is also 100% allowed in Seurat
```R
> data("pbmc_small")
> pbmc_small[["RNAv5"]] <- as(pbmc_small[["RNA"]], Class = "Assay5")
Warning message:
Key ‘rna_’ taken, using ‘rnav5_’ instead
> pbmc_small
An object of class Seurat
460 features across 80 samples within 2 assays
Active assay: RNA (230 features, 20 variable features)
 3 layers present: counts, data, scale.data
 1 other assay present: RNAv5
 2 dimensional reductions calculated: pca, tsne
> pbmc_small[["RNA"]]
Assay data with 230 features for 80 cells
Top 10 variable features:
 PPBP, IGLL5, VDAC3, CD1C, AKR1C3, PF4, MYL9, GNLY, TREML1, CA2
> pbmc_small[["RNAv5"]]
Assay (v5) data with 230 features for 80 cells
Top 10 variable features:
 PPBP, IGLL5, VDAC3, CD1C, AKR1C3, PF4, MYL9, GNLY, TREML1, CA2
Layers:
 data, counts, scale.data
```

Finally, we also strongly recommed that you not use `@` to traverse the object structure. We do make changes to the internal structure, and given that v3 and v5 assays are fundamentally different, trying to remember how to use `@` is only going to lead to more fragile code. Instead, we recommend using the official data accessors. For example:
 - use `[[` to pull an assay from a `Seurat` object à la `pbmc_small[["RNA"]]`
 - use `LayerData()` to pull an expression matrix (formerly called a `slot`, now called a `layer`) à la `LayerData(pbmc_small, "scale.data")`
   - Note, this works at both the `Seurat` and assay level, so if you've pulled an assay out, you can still call `LayerData()` on it
   - As a shorthand, you can use `$` on both v3 and v5 assays to pull a layer out. This is chainable with `[[` so something like `pbmc_small[["RNA"]]$scale.data` is 100% valid and supported
 - Use `Cells()` or `Features()` to pull the cell names or feature names from your objects
   - you can also use `colnames()` and `rownames()` at the `Seurat` level or on v3 assays to get the same information; on v5 assays, this works a little differently due to the multi-layered nature of v5 assays
 - Use `nrow()`, `ncol()`, and `dim()` to get the number of features and cells in your objects
   - At the `Seurat` level, these numbers may change as the default assay and features within the default assay changes

**Comment by vertesy** [comment]
Hey Paul, 

Thank you for the detailed explanation and solution, I will try out the command you returned. 

I would still recommend adding a warning line like `Did not transform assays XYZ from the v3 spec to the v5 spec!`. Naively you would precisely expect that to happen.

On your note about how to access data, I followed this principle before, but I can't really trust some of those functions, see: https://github.com/satijalab/seurat-object/issues/201 for one example. I [built several functions on top of Seurat](https://github.com/vertesy/Seurat.utils), and upon the v3 > v5 change access functions caused me more problem than `@` access (cleaner break). So now I reverted to using `@` and co.  
Also because issues like this one arise, it is better for me to know the internal structure instead of cluelessly staring at a FetchData error on a "black-box" object. Anyways, this is just my way.

Thanks a lot,
Abel

**Comment by vertesy** [comment]
Also, could you please update the Help along the lines of the above warnings

Currently:
- Title: `Update old Seurat object to accommodate new features`
- Description: `Updates Seurat objects to new structure for storing data/calculations. For Seurat v3 objects, will validate object structure ensuring all keys and feature names are formed properly.`

I think it could benefit from a more explicit description of what is intended or not, and what the user can / cannot expect.

Thanks!

**Comment by vertesy** [comment]
Also, there are 2 typos in the first line of code you suggested

```r
object[["assay_name"]] <- as(object[["assay_name", class = "Assay5")
# ]]
# smaller case class
```

```r
# smaller case class
as(pbmc_small[["RNA"]], class = "Assay5")
Error in as(combined.obj[["RNA"]], class = "Assay5") : 
  unused argument (class = "Assay5")
```


Correct, as:
```r
> as(pbmc_small[["RNA"]], Class = "Assay5")
Assay (v5) data with 230 features for 80 cells
Top 10 variable features:
 PPBP, IGLL5, VDAC3, CD1C, AKR1C3, PF4, MYL9, GNLY, TREML1, CA2 
Layers:
 data, counts, scale.data 
```
